### ISSUE TITLE
3rdparty/libuv/src/uv-common.h:41:24: fatal error: stdatomic.h: No such file or directory

### ISSUE THREAD

**Issue by demanuel** [MoarVM/MoarVM#1759]
Hi!

I'm trying to compile the latest version of moarvm (with rakubrew) and it fails with:

```
compiling 3rdparty/libuv/src/unix/linux.o
In file included from 3rdparty/libuv/src/unix/internal.h:25:0,
                 from 3rdparty/libuv/src/unix/linux.c:27:
3rdparty/libuv/src/uv-common.h:41:24: fatal error: stdatomic.h: No such file or directory
 # include <stdatomic.h>
                        ^
compilation terminated.
make: *** [3rdparty/libuv/src/unix/linux.o] Error 1
Command failed (status 512): /home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --optimize --git-cache-dir=/home/ux992/.rakubrew/git_reference --prefix=/home/ux992/.rakubrew/versions/moar-2023.05
/install --make-install
 at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /home/ux992/perl5/perlbrew/perls"...) called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 1502
        NQP::Config::system_or_die("/home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl", "Configure.pl", "--optimize", "--git-cache-dir=/home/ux992/.rakubrew/git_reference", "--prefix=/home/ux992/.rakubrew/ve
rsions/moar-2023.05/install", "--make-install") called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/tools/lib/NQP/Config/NQP.pm line 427
        NQP::Config::NQP::gen_moar(NQP::Config::NQP=HASH(0x19585c8)) called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/tools/lib/NQP/Config/NQP.pm line 105
        NQP::Config::NQP::configure_moar_backend(NQP::Config::NQP=HASH(0x19585c8)) called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 666
        NQP::Config::configure_active_backends(NQP::Config::NQP=HASH(0x19585c8)) called at Configure.pl line 137
Command failed (status 512): /home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --prefix=/home/ux992/.rakubrew/versions/moar-2023.05/install --make-install --git-protocol=https --no-relocatable -
-no-ignore-errors --silent-build --no-force-rebuild --git-cache-dir=/home/ux992/.rakubrew/git_reference --backends=moar --gen-moar
 at /home/ux992/.rakubrew/versions/moar-2023.05/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /home/ux992/perl5/perlbrew/perls"...) called at /home/ux992/.rakubrew/versions/moar-2023.05/3rdparty/nqp-configure/lib/NQP/Config.pm line 1502
        NQP::Config::system_or_die("/home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl", "Configure.pl", "--prefix=/home/ux992/.rakubrew/versions/moar-2023.05/install", "--make-install", "--git-protocol=https
", "--no-relocatable", "--no-ignore-errors", "--silent-build", "--no-force-rebuild", ...) called at /home/ux992/.rakubrew/versions/moar-2023.05/tools/lib/NQP/Config/Rakudo.pm line 719
        NQP::Config::Rakudo::gen_nqp(NQP::Config::Rakudo=HASH(0x1a2a5c8)) called at Configure.pl line 145
Failed running /home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --backends=moar --gen-moar --make-install  --git-cache-dir="/home/ux992/.rakubrew/git_reference" at /home/ux992/Applications/raku
brew/bin/rakubrew line 752.
```

Is there any workaround to not use the latest version of libuv ? (since i didn't had this error before, I'm assuming that the issue is caused by the update to the latest libuv version).

server Red Hat Enterprise Linux Server release 7.9 (Maipo), with gcc 4.8.5

**Comment by MasterDuke17** [comment]
You could try the ‘--has-libuv’ option for Configure.pl to use the system one.Sent from my iPhoneOn Jun 8, 2023, at 6:56 PM, David Emanuel Santiago ***@***.***> wrote:﻿
Hi!
I'm trying to compile the latest version of moarvm (with rakubrew) and it fails with:
compiling 3rdparty/libuv/src/unix/linux.o
In file included from 3rdparty/libuv/src/unix/internal.h:25:0,
                 from 3rdparty/libuv/src/unix/linux.c:27:
3rdparty/libuv/src/uv-common.h:41:24: fatal error: stdatomic.h: No such file or directory
 # include <stdatomic.h>
                        ^
compilation terminated.
make: *** [3rdparty/libuv/src/unix/linux.o] Error 1
Command failed (status 512): /home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --optimize --git-cache-dir=/home/ux992/.rakubrew/git_reference --prefix=/home/ux992/.rakubrew/versions/moar-2023.05
/install --make-install
 at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /home/ux992/perl5/perlbrew/perls"...) called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 1502
        NQP::Config::system_or_die("/home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl", "Configure.pl", "--optimize", "--git-cache-dir=/home/ux992/.rakubrew/git_reference", "--prefix=/home/ux992/.rakubrew/ve
rsions/moar-2023.05/install", "--make-install") called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/tools/lib/NQP/Config/NQP.pm line 427
        NQP::Config::NQP::gen_moar(NQP::Config::NQP=HASH(0x19585c8)) called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/tools/lib/NQP/Config/NQP.pm line 105
        NQP::Config::NQP::configure_moar_backend(NQP::Config::NQP=HASH(0x19585c8)) called at /home/ux992/.rakubrew/versions/moar-2023.05/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 666
        NQP::Config::configure_active_backends(NQP::Config::NQP=HASH(0x19585c8)) called at Configure.pl line 137
Command failed (status 512): /home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --prefix=/home/ux992/.rakubrew/versions/moar-2023.05/install --make-install --git-protocol=https --no-relocatable -
-no-ignore-errors --silent-build --no-force-rebuild --git-cache-dir=/home/ux992/.rakubrew/git_reference --backends=moar --gen-moar
 at /home/ux992/.rakubrew/versions/moar-2023.05/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /home/ux992/perl5/perlbrew/perls"...) called at /home/ux992/.rakubrew/versions/moar-2023.05/3rdparty/nqp-configure/lib/NQP/Config.pm line 1502
        NQP::Config::system_or_die("/home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl", "Configure.pl", "--prefix=/home/ux992/.rakubrew/versions/moar-2023.05/install", "--make-install", "--git-protocol=https
", "--no-relocatable", "--no-ignore-errors", "--silent-build", "--no-force-rebuild", ...) called at /home/ux992/.rakubrew/versions/moar-2023.05/tools/lib/NQP/Config/Rakudo.pm line 719
        NQP::Config::Rakudo::gen_nqp(NQP::Config::Rakudo=HASH(0x1a2a5c8)) called at Configure.pl line 145
Failed running /home/ux992/perl5/perlbrew/perls/perl-5.20.3/bin/perl Configure.pl --backends=moar --gen-moar --make-install  --git-cache-dir="/home/ux992/.rakubrew/git_reference" at /home/ux992/Applications/raku
brew/bin/rakubrew line 752.

Is there any workaround to not use the latest version of libuv ? (since i didn't had this error before, I'm assuming that the issue is caused by the update to the latest libuv version).
server Red Hat Enterprise Linux Server release 7.9 (Maipo), with gcc 4.8.5

**Comment by demanuel** [comment]
Unable to compile :-(

```
 ./Configure.pl --has-libuv --optimize --git-cache-dir=/home/ux992/.rakubrew/git_reference --prefix=/home/ux992/.rakubrew/versions/moar-main/install --make-install
Welcome to MoarVM!

Updating submodules .................................... OK
Configuring native build environment ...................
    trying to compile a simple C program ............... YES
    probing support of -Werror=* ....................... YES
    Testing pkgconfig .................................. 0.27.1
Package libuv was not found in the pkg-config search path.
Perhaps you should add the directory containing `libuv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libuv' found
Error occured when running /usr/bin/pkg-config --cflags libuv.
Package libuv was not found in the pkg-config search path.
Perhaps you should add the directory containing `libuv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libuv' found
Error occured when running /usr/bin/pkg-config --libs-only-L libuv.
    probing stdatomic .................................. NO
did not find libzstd; will not use heap snapshot format version 3
Defaulting to libc malloc because <stdatomic.h> was not found.
OK

```

**Comment by niner** [comment]
On Friday, 9 June 2023 15:38:46 CEST David Emanuel Santiago wrote:
> Unable to compile :-(

Have you installed the appropriate libuv-devel or -dev or whatever it's called 
on that distro package?

**Comment by demanuel** [comment]
just checked and nope i don't have it. Can i compile without libuv? If not how can i build with rakubrew the version 2023.04 ?

**Comment by patrickbkr** [comment]
This is a RHEL 7 which is equivalent to CentOS 7. That's the same system we are currently having trouble with to get the precompiled packages building. What needs to happen to make the build work is to somehow install a GCC that is newer than 4.9 (if I recall correctly).

One can use https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/ to get a recent GCC on such a system.

@MasterDuke17 I think you said you know about some other way to install a more recent GCC on CentOS ("module" command?). Can you elaborate?

**Comment by demanuel** [comment]
@patrickbkr Unfortunately i'm unable to install any packages as i'm not the admin :-(

**Comment by MasterDuke17** [comment]
Yeah, on the Centos7 systems I use there is a ‘module’ command that’s sort of like a virtual env, i.e., it will install non-system versions of programs and make the proper environment variable edits so they’re available. So something like ‘module avail gcc’ should show you what versions you can install (I think I have up to gcc 11 I can use on my system).Sent from my iPhoneOn Jun 11, 2023, at 12:06 PM, David Emanuel Santiago ***@***.***> wrote:﻿
@patrickbkr Unfortunately i'm unable to install any packages as i'm not the admin :-(

**Comment by patrickbkr** [comment]
@MasterDuke17 I think this is the [Environment Modules](https://modules.readthedocs.io/) project at work. Not installed by default but can be installed.

**Comment by MasterDuke17** [comment]
Ah, I thought it was installed by default, my bad.Sent from my iPhoneOn Jun 14, 2023, at 4:24 PM, Patrick Böker ***@***.***> wrote:﻿
@MasterDuke17 I think this is the Environment Modules project at work. Not installed by default but can be installed.

**Comment by patrickbkr** [comment]
In the pipeline used to build the precompiled release files on rakudo.org this is now fixed with https://github.com/rakudo/rakudo/commit/1de53a4b5fc3d5fcd177d11a054e1ef4365da629

**Comment by patrickbkr** [comment]
@demanuel Given this issue is now well understood, there is a workaround available (build with a GCC >= 4.9), and precompiled release files hopefully being available soon-ish (it's still unclear whether we'll do a 2023.05.1 point release or just skip to 2023.06), do you consider this issue solved?

**Comment by demanuel** [comment]
i understand the solution, but i still have the problem since i'm unable to install packages (not the machine admin). :-(

Since this is an environmental issue, i guess it can be close.

**Comment by demanuel** [comment]
@patrickbkr YES! :-)

I didn't know i could download executables and not building them :-D

```
 > rakubrew list
  system
* moar-2023.04
  moar-2023.06
BROKEN   moar-main
  moar-master
 > raku
Welcome to Rakudo™ v2023.06.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.06.

You may want to `zef install Readline`, `zef install Linenoise`, or `zef install Terminal::LineEditor` or use rlwrap for a line editor

To exit type 'exit' or '^D'
[0] >
```
