### ISSUE TITLE
Windows failures: `rc\jit\x64\emit.dasc:2892: error: missing operand size in `mov x?,i?'`

### ISSUE THREAD

**Issue by zoffixznet** [MoarVM/MoarVM#892]
There are fresh failures in Appveyor when building Rakudo: https://ci.appveyor.com/project/rakudo/rakudo/build/1.0.2031/job/exulagft9fdj5gb3

```
	cl /nologo /MT /Ox /GL /DNDEBUG  /DWIN32 /DAO_ASSUME_WINDOWS98 /DMVM_TRACING=0 /DMVM_CGOTO=0 /DMVM_RDTSCP=1 /nologo /LTCG 3rdparty\dynasm\minilua.c -o 3rdparty\dynasm\minilua.exe shell32.lib ws2_32.lib mswsock.lib rpcrt4.lib advapi32.lib psapi.lib iphlpapi.lib userenv.lib user32.lib
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
cl : Command line warning D9002 : ignoring unknown option '/LTCG'
minilua.c
Generating code
Finished generating code
preprocessing src\jit\x64\emit.dasc
src\jit\x64\emit.dasc:2892: error: missing operand size in `mov x?,i?':
        | mov ARG5, 0;                           // NULL to &was_multi
src\jit\x64\emit.dasc:*: info: 1 error in input file -- no output file generated.
```

They look to have started recently, with [one of these commits](https://github.com/perl6/nqp/commit/cec76ff79) being suspect as rakudo started failing when those were version-bumped into it and the `moar=master` version of Appveyor was failing earlier than that.

**Comment by samcv** [comment]
I think this is fixed now?

**Comment by zoffixznet** [comment]
> I think this is fixed now?

Hard to say. Rakudo's AppVeyor [still fails](https://ci.appveyor.com/project/rakudo/rakudo/build/1.0.2053/job/pbwi9f6sve6uftnn), but with a different error:

```
 Creating library dynext/perl6_ops_moar.lib and object dynext/perl6_ops_moar.exp
container.obj : error LNK2001: unresolved external symbol MVM_serialization_write_ref
container.obj : error LNK2001: unresolved external symbol MVM_serialization_read_ref
dynext/perl6_ops_moar.dll : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\link.EXE"' : return code '0x460'

```

**Comment by jnthn** [comment]
That's a different error, far later in the build, and is addressed in https://github.com/MoarVM/MoarVM/commit/d4d8ff4159. Closing the ticket here; there's one in the Rakudo repo that we can use to track this until version bumps are done and we verify it really deals with the issue.
